language: rust
rust:
  - stable
  - nightly
script:
  - cargo test --verbose --no-fail-fast
  - cargo test --verbose --no-fail-fast --features fpbkdf2
  - cargo test --verbose --no-fail-fast --features "fpbkdf2 fuzzy_tests" --release
