[package]
name = "djangohashers"
version = "0.2.1"
authors = ["Ronaldo Racum <ronaldo@racum.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/racum/rust-djangohashers"
keywords = ["hash", "password", "python", "django", "crypto"]
description = "A Rust port of the password primitives used in Django project."

[lib]
doc = true
doctest = false
bench = true

[features]
default = []
fpbkdf2 = ["fastpbkdf2"]

[dependencies]
rust-crypto = "^0.2"
bcrypt = "^0.1"
rustc-serialize = "^0.3"
rand = "^0.3"
fastpbkdf2 = { version = "0.1.0", optional = true }
